---
title: "Overview"
---

Salinity affects both biological and physical components of the ocean ecosystem, including growth rates of marine organisms and vertical stratification [@RN13951; @RN14209].

Different species and life stages have preferred salinity conditions, outside of which they experience harmful physiological effects, including mortality [@RN7554; @RN14209]. Many organisms are expected to shift their spatial distribution to avoid poor environmental conditions [@RN13620], although sessile and cultured organisms have limited to no ability to do so. Salinity is of particular concern for shellfish aquaculture. For example, two cultured species in Nova Scotia (blue mussels and oysters) can tolerate a wide range of salinity for short periods of time, but prolonged exposure to low salinity (e.g., from freshwater pulses) can result in reduced growth and reproduction, higher disease prevalence, and eventually death [@RN14209; @RN14690].

Like temperature, salinity is directly related to seasonal ocean stratification. Freshwater inputs in the spring and summer contribute to a fresh, warm surface layer that is broken down by wind-driven mixing in the fall and winter. Salinity is also influenced by rates of evaporation and precipitation, melting and freezing of sea ice, and ocean circulation [@RN13951].

Surface waters around Canada, including off the coast of Nova Scotia, are generally becoming fresher due to climate change and natural variability [@RN13951]. This trend is expected to continue as a result of the projected increase in precipitation and ice melt [@RN13951; @RN14690]. In contrast, deep waters in the Gulf of St. Lawrence are becoming more saline as a result of a northward shift of subtropical currents bringing in saltier waters [@RN13951; @RN14690]. 


