---
title: "Overview"
---

Temperature is a key driver of biological and physical components of the marine ecosystem.

Ocean temperature is a critical parameter for marine life, influencing physiological processes, species distribution, and species abundance [@RN12876]. Warming temperatures have been linked to individual and population-level changes in fish species, including decreased body size [@RN13690] and range expansions or shifts towards cooler, deeper waters [@RN13620; @RN7236]. For example, several species typically associated with warm waters south of Nova Scotia are now considered "well established" on the Scotian Shelf (e.g., the blackbelly rosefish, *Helicolenus dactylopterus*), and more warm-water species are expected to become established as temperatures increase [@RN15387].

Temperature is directly related to ocean stratification, which occurs when layers of water with different densities (driven by differences in temperature and salinity) form on top of each other and limit mixing. Upper ocean stratification is seasonal, with a warm, fresh layer that develops in the spring and summer (e.g., from surface warming and freshwater inputs) and mixes with deeper waters in the fall and winter (e.g., from wind-driven mixing). This seasonal mixing brings heat and carbon dioxide into deeper waters and transports nutrients from deep waters to the euphotic zone, supporting the base of the food web [@RN13951]. There is evidence that stratification in some regions of Atlantic Canada is increasing due to changes in temperature and salinity [@RN15284]. Increased stratification has implications for climate change (e.g., reduced ability to absorb carbon dioxide) and the ecosystem (e.g., fewer nutrients available for phytoplankton).
